### ISSUE TITLE
The code ran twice and then stopped working.

### ISSUE THREAD

**Issue by Paras2004** [Persimus/DeepDream#1]
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in 
a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in 
a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Anaconda3\envs\deepdream\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in 
a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
Starting  WhatsApp Image 2022-02-01 at 10.29.50 PM(4).jpg
Traceback (most recent call last):
  File "c:/Users/xxxx/Downloads/DeepDream-master/dream_image.py", line 43, in <module>
    num_repeats=25, blend=0.2)
  File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 309, in recursive_optimize
    tile_size=tile_size)
  File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 309, in recursive_optimize
    tile_size=tile_size)
  File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 309, in recursive_optimize
    tile_size=tile_size)
  [Previous line repeated 6 more times]
  File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 298, in recursive_optimize
    factor=rescale_factor)
  File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 104, in resize_image
    img_resized = img.resize(size, PIL.Image.LANCZOS)
  File "C:\Anaconda3\envs\deepdream\lib\site-packages\PIL\Image.py", line 1980, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0

**Comment by Persimus** [comment]
First try to rollback any changes you made and try other JPG file.
As the issue seems to be related to the image resizing.

The issue can be seems to be caused by image processing
```
File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 298, in recursive_optimize
factor=rescale_factor)
File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 104, in resize_image
img_resized = img.resize(size, PIL.Image.LANCZOS)
File "C:\Anaconda3\envs\deepdream\lib\site-packages\PIL\Image.py", line 1980, in resize
return self._new(self.im.resize(size, resample, box))
ValueError: height and width must be > 0
```

**Comment by Paras2004** [comment]
> First try to rollback any changes you made and try other JPG file. As the issue seems to be related to the image resizing.
> 
> The issue can be seems to be caused by image processing
> 
> ```
> File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 298, in recursive_optimize
> factor=rescale_factor)
> File "c:\Users\xxxx\Downloads\DeepDream-master\deepdreamer.py", line 104, in resize_image
> img_resized = img.resize(size, PIL.Image.LANCZOS)
> File "C:\Anaconda3\envs\deepdream\lib\site-packages\PIL\Image.py", line 1980, in resize
> return self._new(self.im.resize(size, resample, box))
> ValueError: height and width must be > 0
> ```

I reversed the changes and the num_repeats value increase seems the problem, however, without increasing the value, the deep dream seems quite less. Can you help me?
